service:
  name: SABS-lambda

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, 'prod'}


  iamRoleStatements:
   - Effect: "Allow"
     Action:
       - "s3:*"
      #  - "s3:ListBucket"
      #  - "s3:GetObject"
     Resource:
       - "Fn::Join":
         - ""
         -
           - "arn:aws:s3:::"
           - "codepipeline-"
           - "Ref" : "AWS::Region"
           - "-*"
   - Effect: "Allow"
     Action:
       - "ec2:CreateImage"
       - "ec2:DescribeInstances"
       - "ec2:DescribeImages"
     Resource: "*"
   - Effect: "Allow"
     Action:
       - "codepipeline:PutJobSuccessResult"
       - "codepipeline:PutJobFailureResult"
     Resource: "*"

  #  - Effect: "Allow"
  #    Action:
  #      - "dynamodb:*"
  #    Resource:
  #      - "Fn::Join":
  #        - ""
  #        -
  #          - "arn:aws:dynamodb:"
  #          - "Ref" : "AWS::Region"
  #          - ":"
  #          - "Ref" : "AWS::AccountId"
  #          - ":table/${self:custom.DynamoDBTableName}"
  #      - "Fn::Join":
  #        - ""
  #        -
  #          - "arn:aws:dynamodb:"
  #          - "Ref" : "AWS::Region"
  #          - ":"
  #          - "Ref" : "AWS::AccountId"
  #          - ":table/${self:custom.DynamoDBTableName}/*"
   - Effect: "Allow"
     Action:
       - "cloudformation:DeleteStack"
     Resource:
       - "Fn::Join":
         - ""
         -
           - "arn:aws:cloudformation:"
           - "Ref" : "AWS::Region"
           - ":"
           - "Ref" : "AWS::AccountId"
           - ":stack/*"


functions:
  create-ami:
    handler: src/create-ami.run
    environment:
      snapShotDescription: SABS engine snapshot
